import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header style={{ fontFamily: "var(--font-geist-sans)", padding: "1rem", backgroundColor: "#35494e" }}>
          <h1>[Header in About Layout] About</h1>
        </header>
        {children}
        <footer style={{ fontFamily: "var(--font-geist-mono)", padding: "1rem", backgroundColor: "#443d3d" }}>
          <p>[Footer in About Layout] © 2024 My App. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
