import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header style={{ fontFamily: "var(--font-geist-sans)", padding: "1rem", backgroundColor: "#35494e" }}>
          <h1>My App</h1>
        </header>
        {children}
        <footer style={{ fontFamily: "var(--font-geist-mono)", padding: "1rem", backgroundColor: "#443d3d" }}>
          <p>© 2024 My App. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
